# Stage 1: Build
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx ng build --configuration production



# Stage 2: Serve with Nginx
FROM nginx:alpine
# Copy the build output to Nginx's default public folder
COPY --from=build /app/dist/dnc_frontend/browser /usr/share/nginx/html

# Copy our custom nginx config
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
