// generated by sea-orm-cli migrate generate create_table_dataobject
use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_orm::{ConnectionTrait};
use sea_orm_migration::sea_query::{PostgresQueryBuilder, Expr};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {

        // 1. Create Table
        // DataObjects are the objects (essentially db tables) that we need to maintain permissions for.
        // I've removed the dataobjects and permissions as DataObjects as these are internal tables
        // no user would ever need to add to or modify.
        // Instead, we have:
        // 1. dental_service
        // 2. clinic_capabilities
        // 3. user
        // 4. role
        // 5. role_permission
        // 6. hmo
        // 7. dental_contract
        // 8. clinic
        // 9. dentist
        // 10. endorsement
        manager
            .create_table(
                Table::create()
                    .table(DataObject::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(DataObject::Id)
                        .integer()
                        .not_null()
                        .auto_increment()
                        .primary_key()
                    )
                    .col( ColumnDef::new(DataObject::Name)
                        .string()
                        .not_null()
                    )
                    .col(ColumnDef::new(DataObject::Description)
                        .string()
                    )
                    .to_owned(),
            )
            .await?;

        // 2. Create Index
        manager
            .create_index(
                Index::create()
                    .name("idx_dataobject_name")
                    .table(DataObject::Table)
                    .col(DataObject::Name)
                    .unique()
                    .to_owned(),
            ).await?;

        // 3.Insert Initial Data
        Self::add_dataobject(manager, "dental_service", "dental_service Data Object").await?;
        Self::add_dataobject(manager, "clinic_capability", "clinic_capability Data Object").await?;
        Self::add_dataobject(manager, "user", "user Data Object").await?;
        Self::add_dataobject(manager, "role", "permission Data Object").await?;
        Self::add_dataobject(manager, "role_permission", "role_permission Data Object").await?;
        Self::add_dataobject(manager, "hmo", "hmo Data Object").await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_index(Index::drop().name("idx_dataobject_name").table(DataObject::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table("dataobject").to_owned())
            .await?;
        Ok(())
    }
}
impl Migration {
    pub async fn add_dataobject(manager: &SchemaManager<'_>, name: &str, description: &str)->Result<(), DbErr>{
        // 1. Create Insert Statement
        let insert = Query::insert()
            .into_table(DataObject::Table)
            .columns([DataObject::Name, DataObject::Description])
            .values_panic([Expr::val(name), Expr::val(description)])
            .to_owned();
        // 2. Force Postgres formatting
        let sql= insert.to_string(PostgresQueryBuilder);

        //3. Execute
        manager
            .get_connection()
            .execute_unprepared(&sql)
            .await?;

        Ok(())

    }
}

#[derive(DeriveIden)]
pub enum DataObject {
    Table,
    Id,
    Name,
    Description,
}