// generated by sea-orm-cli migrate generate create_table_dataobject
use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_orm::{ConnectionTrait};
use sea_orm_migration::sea_query::{PostgresQueryBuilder, Expr};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {

        // 1. Create Table
        manager
            .create_table(
                Table::create()
                    .table(DataObject::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(DataObject::Id)
                        .integer()
                        .not_null()
                        .auto_increment()
                        .primary_key()
                    )
                    .col( ColumnDef::new(DataObject::Name)
                        .string()
                        .not_null()
                    )
                    .col(ColumnDef::new(DataObject::Description)
                        .string()
                    )
                    .to_owned(),
            )
            .await?;

        // 2. Create Index
        manager
            .create_index(
                Index::create()
                    .name("idx_dataobject_name")
                    .table(DataObject::Table)
                    .col(DataObject::Name)
                    .unique()
                    .to_owned(),
            ).await?;

        // 3.Insert Initial Data
        Self::add_dataobject(manager, "dataobject", "dataobject Data Object").await?;
        Self::add_dataobject(manager, "permission", "permission Data Object").await?;
        Self::add_dataobject(manager, "user", "user Data Object").await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_index(Index::drop().name("idx_dataobject_name").table(DataObject::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table("dataobject").to_owned())
            .await?;
        Ok(())
    }
}
impl Migration {
    async fn add_dataobject(manager: &SchemaManager<'_>, name: &str, description: &str)->Result<(), DbErr>{
        // 1. Create Insert Statement
        let insert = Query::insert()
            .into_table(DataObject::Table)
            .columns([DataObject::Name, DataObject::Description])
            .values_panic([Expr::val(name), Expr::val(description)])
            .to_owned();
        // 2. Force Postgres formatting
        let sql= insert.to_string(PostgresQueryBuilder);

        //3. Execute
        manager
            .get_connection()
            .execute_unprepared(&sql)
            .await?;

        Ok(())

    }
}

#[derive(DeriveIden)]
pub enum DataObject {
    Table,
    Id,
    Name,
    Description,
}