// generated by sea-orm-cli migrate generate create_table_dataobject
use sea_orm_migration::{prelude::*, schema::pk_auto};
use sea_orm_migration::schema::string;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Replace the sample below with your own migration scripts

        manager
            .create_table(
                Table::create()
                    .table(DataObject::Table)
                    .if_not_exists()
                    .col(pk_auto(DataObject::Id ))
                    .col( ColumnDef::new(DataObject::Name)
                        .string()
                        .not_null())
                    .col(string(DataObject::Description))
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_dataobject_name")
                    .table(DataObject::Table)
                    .col(DataObject::Name)
                    .to_owned(),
        ).await?;

        let insert = Query::insert()
            .into_table(DataObject::Table)
            .columns([DataObject::Name, DataObject::Description])
            .values_panic(["User".into(), "User Table".into()])
            .to_owned();

        manager.execute(insert).await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_index(Index::drop().name("idx_dataobject_name").table(DataObject::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table("dataobject").to_owned())
            .await?;
        Ok(())
    }
}

#[derive(DeriveIden)]
pub enum DataObject {
    Table,
    Id,
    Name,
    Description,
}