### request to example server
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "admin@dnc.com.ph",
  "password": "password"
}



###
POST http://localhost:3000/test_post
Content-Type: application/json

{
  "name": "admin@dnc.com.ph",
  "message": "Hello, there!"
}
