//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "acc_reconciliation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date_created: DateTimeWithTimeZone,
    pub created_by: String,
    pub dentist_id: i32,
    pub dental_service_id: i32,
    pub date_service_performed: Option<Date>,
    pub approved_by: Option<String>,
    pub approval_date: Option<DateTimeWithTimeZone>,
    pub approval_code: Option<String>,
    pub tooth_id: Option<String>,
    pub tooth_service_type_id: Option<i32>,
    pub tooth_surface_id: Option<i32>,
    pub member_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dental_service::Entity",
        from = "Column::DentalServiceId",
        to = "super::dental_service::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentalService,
    #[sea_orm(
        belongs_to = "super::dentist::Entity",
        from = "Column::DentistId",
        to = "super::dentist::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Dentist,
    #[sea_orm(
        belongs_to = "super::tooth_service_type::Entity",
        from = "Column::ToothServiceTypeId",
        to = "super::tooth_service_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ToothServiceType,
    #[sea_orm(
        belongs_to = "super::tooth_surface::Entity",
        from = "Column::ToothSurfaceId",
        to = "super::tooth_surface::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ToothSurface,
}

impl Related<super::dental_service::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentalService.def()
    }
}

impl Related<super::dentist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dentist.def()
    }
}

impl Related<super::tooth_service_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ToothServiceType.def()
    }
}

impl Related<super::tooth_surface::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ToothSurface.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
