//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19
#[allow(unused_imports)]
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "city")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "city_name_province_id_index")]
    pub name: String,
    #[sea_orm(unique_key = "city_name_province_id_index")]
    pub province_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dental_clinic::Entity")]
    DentalClinic,
    #[sea_orm(
        belongs_to = "super::province::Entity",
        from = "Column::ProvinceId",
        to = "super::province::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Province,
}

impl Related<super::dental_clinic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentalClinic.def()
    }
}

impl Related<super::province::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Province.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
