//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "clinic_capabilities_list")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub clinic_id: i32,
    pub capability_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinic_capability::Entity",
        from = "Column::CapabilityId",
        to = "super::clinic_capability::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ClinicCapability,
    #[sea_orm(
        belongs_to = "super::dental_clinic::Entity",
        from = "Column::ClinicId",
        to = "super::dental_clinic::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentalClinic,
}

impl Related<super::clinic_capability::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClinicCapability.def()
    }
}

impl Related<super::dental_clinic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentalClinic.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
