//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "contact_us_messages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date_submitted: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub person_type: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub card_number: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub company_and_hmo: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub contact_numbers: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
