//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dentist_clinic")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub dentist_id: i32,
    pub clinic_id: Option<i32>,
    pub position: Option<String>,
    pub schedule: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dental_clinic::Entity",
        from = "Column::ClinicId",
        to = "super::dental_clinic::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentalClinic,
    #[sea_orm(
        belongs_to = "super::dentist::Entity",
        from = "Column::DentistId",
        to = "super::dentist::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Dentist,
}

impl Related<super::dental_clinic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentalClinic.def()
    }
}

impl Related<super::dentist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dentist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
