//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dentist")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub last_name: String,
    pub given_name: String,
    pub middle_initial: String,
    pub email: Option<String>,
    #[sea_orm(column_type = "Float")]
    pub retainer_fee: f32,
    pub dentist_status_id: Option<i32>,
    pub dentist_history_id: Option<i32>,
    pub dentist_requested_by: Option<String>,
    pub accre_dentist_contract_id: Option<i32>,
    pub accre_document_code: Option<String>,
    pub accreditation_date: Option<String>,
    pub accre_contract_sent_date: Option<String>,
    pub accre_contract_file_path: Option<String>,
    pub acc_tin: Option<String>,
    pub acc_bank_name: Option<String>,
    pub acc_account_name: Option<String>,
    pub acc_account_number: Option<String>,
    pub acc_tax_type_id: Option<i32>,
    pub acc_tax_classification_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dentist_clinic::Entity")]
    DentistClinic,
    #[sea_orm(
        belongs_to = "super::dentist_contract::Entity",
        from = "Column::AccreDentistContractId",
        to = "super::dentist_contract::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentistContract,
    #[sea_orm(
        belongs_to = "super::dentist_history::Entity",
        from = "Column::DentistHistoryId",
        to = "super::dentist_history::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentistHistory,
    #[sea_orm(
        belongs_to = "super::dentist_status::Entity",
        from = "Column::DentistStatusId",
        to = "super::dentist_status::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentistStatus,
    #[sea_orm(
        belongs_to = "super::tax_classification::Entity",
        from = "Column::AccTaxClassificationId",
        to = "super::tax_classification::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TaxClassification,
    #[sea_orm(
        belongs_to = "super::tax_type::Entity",
        from = "Column::AccTaxTypeId",
        to = "super::tax_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TaxType,
}

impl Related<super::dentist_clinic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistClinic.def()
    }
}

impl Related<super::dentist_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistContract.def()
    }
}

impl Related<super::dentist_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistHistory.def()
    }
}

impl Related<super::dentist_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistStatus.def()
    }
}

impl Related<super::tax_classification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxClassification.def()
    }
}

impl Related<super::tax_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
