//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dental_service")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub type_id: i32,
    pub sort_index: Option<i32>,
    pub record_tooth: bool,
    pub active: bool,
    pub last_modified_by: String,
    pub last_modified_on: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dental_service_type::Entity",
        from = "Column::TypeId",
        to = "super::dental_service_type::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    DentalServiceType,
    #[sea_orm(has_many = "super::dentist_contract_service_rates::Entity")]
    DentistContractServiceRates,
}

impl Related<super::dental_service_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentalServiceType.def()
    }
}

impl Related<super::dentist_contract_service_rates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistContractServiceRates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
