//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dentist_contract_service_rates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub dentist_contract_id: Option<i32>,
    pub service_id: Option<i32>,
    #[sea_orm(column_type = "Float")]
    pub rate: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dental_service::Entity",
        from = "Column::ServiceId",
        to = "super::dental_service::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentalService,
    #[sea_orm(
        belongs_to = "super::dentist_contract::Entity",
        from = "Column::DentistContractId",
        to = "super::dentist_contract::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentistContract,
}

impl Related<super::dental_service::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentalService.def()
    }
}

impl Related<super::dentist_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistContract.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
