//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dentist")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub prc_no: Option<String>,
    pub prc_expiry_date: Option<Date>,
    pub last_name: String,
    pub given_name: String,
    pub middle_name: Option<String>,
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Float")]
    pub retainer_fee: f32,
    pub dentist_status_id: Option<i32>,
    pub dentist_decline_remarks: Option<String>,
    pub dentist_history_id: Option<i32>,
    pub dentist_requested_by: Option<String>,
    pub accre_dentist_contract_id: Option<i32>,
    pub accre_document_code: Option<String>,
    pub accreditation_date: Option<String>,
    pub accre_contract_sent_date: Option<String>,
    pub accre_contract_file_path: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dentist_clinic::Entity")]
    DentistClinic,
    #[sea_orm(
        belongs_to = "super::dentist_contract::Entity",
        from = "Column::AccreDentistContractId",
        to = "super::dentist_contract::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentistContract,
    #[sea_orm(
        belongs_to = "super::dentist_history::Entity",
        from = "Column::DentistHistoryId",
        to = "super::dentist_history::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentistHistory,
    #[sea_orm(has_many = "super::dentist_hmo_relations::Entity")]
    DentistHmoRelations,
    #[sea_orm(
        belongs_to = "super::dentist_status::Entity",
        from = "Column::DentistStatusId",
        to = "super::dentist_status::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentistStatus,
}

impl Related<super::dentist_clinic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistClinic.def()
    }
}

impl Related<super::dentist_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistContract.def()
    }
}

impl Related<super::dentist_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistHistory.def()
    }
}

impl Related<super::dentist_hmo_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistHmoRelations.def()
    }
}

impl Related<super::dentist_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistStatus.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
