//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dentist_payments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_dentist_payments_unique_dentist_year_month")]
    pub dentist_id: i32,
    pub clinic_id: i32,
    #[sea_orm(unique_key = "idx_dentist_payments_unique_dentist_year_month")]
    pub year: i32,
    #[sea_orm(unique_key = "idx_dentist_payments_unique_dentist_year_month")]
    pub month: i32,
    pub report_name: Option<String>,
    pub date_paid: Option<DateTimeWithTimeZone>,
    pub date_paid_recorded_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dental_clinic::Entity",
        from = "Column::ClinicId",
        to = "super::dental_clinic::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentalClinic,
    #[sea_orm(
        belongs_to = "super::dentist::Entity",
        from = "Column::DentistId",
        to = "super::dentist::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Dentist,
}

impl Related<super::dental_clinic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentalClinic.def()
    }
}

impl Related<super::dentist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dentist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
