//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dentist_hmo_relations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub dentist_id: i32,
    pub hmo_id: i32,
    pub is_exclusive_to_hmo: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dentist::Entity",
        from = "Column::DentistId",
        to = "super::dentist::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Dentist,
    #[sea_orm(
        belongs_to = "super::hmo::Entity",
        from = "Column::HmoId",
        to = "super::hmo::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Hmo,
}

impl Related<super::dentist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dentist.def()
    }
}

impl Related<super::hmo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hmo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
