//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dentist_applications")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date_submitted: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub clinic_name: String,
    #[sea_orm(column_type = "Text")]
    pub contact_numbers: String,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub prc_license_file_path: String,
    #[sea_orm(column_type = "Text")]
    pub bir2303_file_path: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub clinic_ownership_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub registration_doc_file_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub supporting_docs_file_path1: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub hmo_affiliations: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub clinic_address: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
