//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "endorsement_billing_rule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub endorsement_id: i32,
    pub min_count: i32,
    pub max_count: i32,
    pub rate: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::endorsement::Entity",
        from = "Column::EndorsementId",
        to = "super::endorsement::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Endorsement,
}

impl Related<super::endorsement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Endorsement.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
