//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "endorsement")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub endorsement_company_id: i32,
    pub endorsement_type_id: i32,
    pub agreement_corp_number: Option<String>,
    pub date_start: Date,
    pub date_end: Date,
    pub endorsement_billing_period_type_id: i32,
    #[sea_orm(column_type = "Float", nullable)]
    pub retainer_fee: Option<Decimal>,
    pub remarks: Option<String>,
    pub endorsement_method: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::endorsement_billing_period_type::Entity",
        from = "Column::EndorsementBillingPeriodTypeId",
        to = "super::endorsement_billing_period_type::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    EndorsementBillingPeriodType,
    #[sea_orm(
        belongs_to = "super::endorsement_company::Entity",
        from = "Column::EndorsementCompanyId",
        to = "super::endorsement_company::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    EndorsementCompany,
    #[sea_orm(
        belongs_to = "super::endorsement_type::Entity",
        from = "Column::EndorsementTypeId",
        to = "super::endorsement_type::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    EndorsementType,
}

impl Related<super::endorsement_billing_period_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EndorsementBillingPeriodType.def()
    }
}

impl Related<super::endorsement_company::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EndorsementCompany.def()
    }
}

impl Related<super::endorsement_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EndorsementType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
