//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "generated_report")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub report_type_id: i32,
    pub file_name: String,
    pub date_generated: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::report_type::Entity",
        from = "Column::ReportTypeId",
        to = "super::report_type::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    ReportType,
}

impl Related<super::report_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
