//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "high_end_verification_information")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub verification_id: i32,
    pub approved_by: Option<String>,
    pub approved_cost: Option<Decimal>,
    pub approval_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::verification::Entity",
        from = "Column::VerificationId",
        to = "super::verification::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Verification,
}

impl Related<super::verification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Verification.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
