//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "hmo")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub short_name: String,
    pub long_name: String,
    pub address: Option<String>,
    pub tax_account_number: Option<String>,
    pub contact_nos: Option<String>,
    pub expect_a_master_list: Option<bool>,
    pub active: bool,
    pub last_modified_by: String,
    pub last_modified_on: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dentist_hmo_relations::Entity")]
    DentistHmoRelations,
}

impl Related<super::dentist_hmo_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentistHmoRelations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
