//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "hmo_billing_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date_generated: DateTimeWithTimeZone,
    pub endorsement_id: i32,
    pub request_key: Option<String>,
    pub master_list_count: Option<i32>,
    pub added_list_count: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::endorsement::Entity",
        from = "Column::EndorsementId",
        to = "super::endorsement::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Endorsement,
}

impl Related<super::endorsement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Endorsement.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
