//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "master_list")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub file_name: String,
    pub endorsement_id: Option<i32>,
    pub uploaded_by: Option<String>,
    pub upload_date: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::endorsement::Entity",
        from = "Column::EndorsementId",
        to = "super::endorsement::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Endorsement,
    #[sea_orm(has_many = "super::master_list_member::Entity")]
    MasterListMember,
}

impl Related<super::endorsement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Endorsement.def()
    }
}

impl Related<super::master_list_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MasterListMember.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
