//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "master_list_member")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub master_list_id: i32,
    pub member_id: i32,
    pub card_no: String,
    pub row_number: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::master_list::Entity",
        from = "Column::MasterListId",
        to = "super::master_list::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MasterList,
    #[sea_orm(
        belongs_to = "super::member::Entity",
        from = "Column::MemberId",
        to = "super::member::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Member,
}

impl Related<super::master_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MasterList.def()
    }
}

impl Related<super::member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Member.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
