//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19
#![allow(unused_imports, dead_code)] // Notice the '!' which applies to the whole file
pub mod prelude;

pub mod clinic_capability;
pub mod data_object;
pub mod dental_service;
pub mod dental_service_type;
pub mod permission;
pub mod role;
pub mod role_permission;
pub mod sea_orm_active_enums;
pub mod user;
