//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use super::sea_orm_active_enums::PermissionActionEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "permission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub data_object_id: i32,
    pub action: PermissionActionEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::data_object::Entity",
        from = "Column::DataObjectId",
        to = "super::data_object::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    DataObject,
    #[sea_orm(has_many = "super::role_permission::Entity")]
    RolePermission,
}

impl Related<super::data_object::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DataObject.def()
    }
}

impl Related<super::role_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RolePermission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
