#![allow(unused_imports)]
//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19
pub use super::data_object::Entity as DataObject;
pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::user::Entity as User;
