//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

pub use super::city::Entity as City;
pub use super::clinic_capabilities_list::Entity as ClinicCapabilitiesList;
pub use super::clinic_capability::Entity as ClinicCapability;
pub use super::data_object::Entity as DataObject;
pub use super::dental_clinic::Entity as DentalClinic;
pub use super::dental_service::Entity as DentalService;
pub use super::dental_service_type::Entity as DentalServiceType;
pub use super::dentist_contract::Entity as DentistContract;
pub use super::dentist_contract_service_rates::Entity as DentistContractServiceRates;
pub use super::hmo::Entity as Hmo;
pub use super::permission::Entity as Permission;
pub use super::region::Entity as Region;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::state::Entity as State;
pub use super::user::Entity as User;
