//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tooth_surface")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::acc_reconciliation::Entity")]
    AccReconciliation,
    #[sea_orm(has_many = "super::verification::Entity")]
    Verification,
}

impl Related<super::acc_reconciliation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccReconciliation.def()
    }
}

impl Related<super::verification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Verification.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
