//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "verification")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date_created: DateTimeWithTimeZone,
    pub created_by: String,
    pub dentist_id: i32,
    pub member_id: i32,
    pub dental_service_id: i32,
    pub date_service_performed: Option<Date>,
    pub status_id: i32,
    pub approved_by: Option<String>,
    pub approval_date: Option<DateTimeWithTimeZone>,
    pub approval_code: Option<String>,
    pub tooth_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dental_service::Entity",
        from = "Column::DentalServiceId",
        to = "super::dental_service::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DentalService,
    #[sea_orm(
        belongs_to = "super::dentist::Entity",
        from = "Column::DentistId",
        to = "super::dentist::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Dentist,
    #[sea_orm(has_one = "super::high_end_files::Entity")]
    HighEndFiles,
    #[sea_orm(has_many = "super::high_end_verification_information::Entity")]
    HighEndVerificationInformation,
    #[sea_orm(
        belongs_to = "super::master_list_member::Entity",
        from = "Column::MemberId",
        to = "super::master_list_member::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    MasterListMember,
    #[sea_orm(
        belongs_to = "super::verification_status::Entity",
        from = "Column::StatusId",
        to = "super::verification_status::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    VerificationStatus,
}

impl Related<super::dental_service::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DentalService.def()
    }
}

impl Related<super::dentist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dentist.def()
    }
}

impl Related<super::high_end_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HighEndFiles.def()
    }
}

impl Related<super::high_end_verification_information::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HighEndVerificationInformation.def()
    }
}

impl Related<super::master_list_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MasterListMember.def()
    }
}

impl Related<super::verification_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VerificationStatus.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
