//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "verification_tooth_surfaces")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_verification_tooth_surfaces_unique")]
    pub verification_id: i32,
    #[sea_orm(unique_key = "idx_verification_tooth_surfaces_unique")]
    pub tooth_surface_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tooth_surface::Entity",
        from = "Column::ToothSurfaceId",
        to = "super::tooth_surface::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    ToothSurface,
    #[sea_orm(
        belongs_to = "super::verification::Entity",
        from = "Column::VerificationId",
        to = "super::verification::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Verification,
}

impl Related<super::tooth_surface::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ToothSurface.def()
    }
}

impl Related<super::verification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Verification.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
